language: haskell

sudo: false

cache:
  directories:
    - $HOME/.stack

before_install:
  - export PATH=/opt/ghc/7.10.2/bin:$PATH

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2

script:
  - stack --no-terminal --skip-ghc-check test
